version: 2

models:
  - name: dim_customer
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: segment
        tests:
          - accepted_values:
              arguments:
                values: [consumer, small_business, enterprise]
  - name: fct_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - relationships:
              arguments:
                to: ref('dim_customer')
                field: customer_id
